require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ClientSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # ClientSession. As you add validations to ClientSession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "username" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ClientSessionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all client_sessions as @client_sessions" do
      user_session = ClientSession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:client_sessions).should eq([user_session])
    end
  end

  describe "GET show" do
    it "assigns the requested clientsession as @clientsession" do
      user_session = ClientSession.create! valid_attributes
      get :show, {:id => user_session.to_param}, valid_session
      assigns(:clientsession).should eq(user_session)
    end
  end

  describe "GET new" do
    it "assigns a new clientsession as @clientsession" do
      get :new, {}, valid_session
      assigns(:clientsession).should be_a_new(ClientSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested clientsession as @clientsession" do
      user_session = ClientSession.create! valid_attributes
      get :edit, {:id => user_session.to_param}, valid_session
      assigns(:clientsession).should eq(user_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ClientSession" do
        expect {
          post :create, {:clientsession => valid_attributes}, valid_session
        }.to change(ClientSession, :count).by(1)
      end

      it "assigns a newly created clientsession as @clientsession" do
        post :create, {:clientsession => valid_attributes}, valid_session
        assigns(:clientsession).should be_a(ClientSession)
        assigns(:clientsession).should be_persisted
      end

      it "redirects to the created clientsession" do
        post :create, {:clientsession => valid_attributes}, valid_session
        response.should redirect_to(ClientSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved clientsession as @clientsession" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientSession.any_instance.stub(:save).and_return(false)
        post :create, {:clientsession => { "username" => "invalid value" }}, valid_session
        assigns(:clientsession).should be_a_new(ClientSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ClientSession.any_instance.stub(:save).and_return(false)
        post :create, {:clientsession => { "username" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested clientsession" do
        user_session = ClientSession.create! valid_attributes
        # Assuming there are no other client_sessions in the database, this
        # specifies that the ClientSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ClientSession.any_instance.should_receive(:update_attributes).with({ "username" => "MyString" })
        put :update, {:id => user_session.to_param, :clientsession => { "username" => "MyString" }}, valid_session
      end

      it "assigns the requested clientsession as @clientsession" do
        user_session = ClientSession.create! valid_attributes
        put :update, {:id => user_session.to_param, :clientsession => valid_attributes}, valid_session
        assigns(:clientsession).should eq(user_session)
      end

      it "redirects to the clientsession" do
        user_session = ClientSession.create! valid_attributes
        put :update, {:id => user_session.to_param, :clientsession => valid_attributes}, valid_session
        response.should redirect_to(user_session)
      end
    end

    describe "with invalid params" do
      it "assigns the clientsession as @clientsession" do
        user_session = ClientSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_session.to_param, :clientsession => { "username" => "invalid value" }}, valid_session
        assigns(:clientsession).should eq(user_session)
      end

      it "re-renders the 'edit' template" do
        user_session = ClientSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ClientSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_session.to_param, :clientsession => { "username" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested clientsession" do
      user_session = ClientSession.create! valid_attributes
      expect {
        delete :destroy, {:id => user_session.to_param}, valid_session
      }.to change(ClientSession, :count).by(-1)
    end

    it "redirects to the client_sessions list" do
      user_session = ClientSession.create! valid_attributes
      delete :destroy, {:id => user_session.to_param}, valid_session
      response.should redirect_to(user_sessions_url)
    end
  end

end
