require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CpasController do

  # This should return the minimal set of attributes required to create a valid
  # Cpa. As you add validations to Cpa, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "email" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CpasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cpas as @cpas" do
      cpa = Cpa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cpas).should eq([cpa])
    end
  end

  describe "GET show" do
    it "assigns the requested cpa as @cpa" do
      cpa = Cpa.create! valid_attributes
      get :show, {:id => cpa.to_param}, valid_session
      assigns(:cpa).should eq(cpa)
    end
  end

  describe "GET new" do
    it "assigns a new cpa as @cpa" do
      get :new, {}, valid_session
      assigns(:cpa).should be_a_new(Cpa)
    end
  end

  describe "GET edit" do
    it "assigns the requested cpa as @cpa" do
      cpa = Cpa.create! valid_attributes
      get :edit, {:id => cpa.to_param}, valid_session
      assigns(:cpa).should eq(cpa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cpa" do
        expect {
          post :create, {:cpa => valid_attributes}, valid_session
        }.to change(Cpa, :count).by(1)
      end

      it "assigns a newly created cpa as @cpa" do
        post :create, {:cpa => valid_attributes}, valid_session
        assigns(:cpa).should be_a(Cpa)
        assigns(:cpa).should be_persisted
      end

      it "redirects to the created cpa" do
        post :create, {:cpa => valid_attributes}, valid_session
        response.should redirect_to(Cpa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cpa as @cpa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpa.any_instance.stub(:save).and_return(false)
        post :create, {:cpa => { "email" => "invalid value" }}, valid_session
        assigns(:cpa).should be_a_new(Cpa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cpa.any_instance.stub(:save).and_return(false)
        post :create, {:cpa => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cpa" do
        cpa = Cpa.create! valid_attributes
        # Assuming there are no other cpas in the database, this
        # specifies that the Cpa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cpa.any_instance.should_receive(:update_attributes).with({ "email" => "MyString" })
        put :update, {:id => cpa.to_param, :cpa => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested cpa as @cpa" do
        cpa = Cpa.create! valid_attributes
        put :update, {:id => cpa.to_param, :cpa => valid_attributes}, valid_session
        assigns(:cpa).should eq(cpa)
      end

      it "redirects to the cpa" do
        cpa = Cpa.create! valid_attributes
        put :update, {:id => cpa.to_param, :cpa => valid_attributes}, valid_session
        response.should redirect_to(cpa)
      end
    end

    describe "with invalid params" do
      it "assigns the cpa as @cpa" do
        cpa = Cpa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpa.any_instance.stub(:save).and_return(false)
        put :update, {:id => cpa.to_param, :cpa => { "email" => "invalid value" }}, valid_session
        assigns(:cpa).should eq(cpa)
      end

      it "re-renders the 'edit' template" do
        cpa = Cpa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cpa.any_instance.stub(:save).and_return(false)
        put :update, {:id => cpa.to_param, :cpa => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cpa" do
      cpa = Cpa.create! valid_attributes
      expect {
        delete :destroy, {:id => cpa.to_param}, valid_session
      }.to change(Cpa, :count).by(-1)
    end

    it "redirects to the cpas list" do
      cpa = Cpa.create! valid_attributes
      delete :destroy, {:id => cpa.to_param}, valid_session
      response.should redirect_to(cpas_url)
    end
  end

end
